/*
* Package : a2a
* Author : S. Hamblett <steve.hamblett@linux.com>
* Date   : 30/06/2026
* Copyright :  S.Hamblett
*/

part of '../../a2a_types.dart';

/// Represents a file, data structure, or other resource generated by an agent during a task.
@JsonSerializable(explicitToJson: true)
class A2AArtifact {
  /// A unique identifier (e.g. UUID) for the artifact within the scope of the task.
  String artifactId = '';

  /// Optional, human-readable name for the artifact.
  String? name;

  /// Optional, human-readable description for the artifact.
  String? description;

  /// An array of content parts that make up the artifact.
  List<A2APart> parts = [];

  /// Optional metadata for extensions. The key is an extension-specific identifier.
  A2ASV? metadata;

  /// The URIs of extensions that are relevant to this Artifact.
  List<String>? extensions;

  @override
  int get hashCode => artifactId.hashCode;

  A2AArtifact();

  factory A2AArtifact.fromJson(Map<String, dynamic> json) =>
      _$A2AArtifactFromJson(json);

  Map<String, dynamic> toJson() => _$A2AArtifactToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is A2AArtifact &&
          runtimeType == other.runtimeType &&
          artifactId == other.artifactId;
}
