/*
* Package : a2a
* Author : S. Hamblett <steve.hamblett@linux.com>
* Date   : 30/06/2026
* Copyright :  S.Hamblett
*/

part of '../../a2a_types.dart';

/// Represents a single, stateful operation or conversation between a client and an agent.
@JsonSerializable(explicitToJson: true)
class A2ATask {
  /// A unique identifier (e.g. UUID) for the task, generated by the server for a new task.
  String id = '';

  /// A server-generated unique identifier (e.g. UUID) for maintaining
  /// context across multiple related tasks or interactions.
  String contextId = '';

  /// The current status of the task, including its state and a descriptive message.
  A2ATaskStatus status = A2ATaskStatus();

  ///  An array of messages exchanged during the task, representing the conversation history.
  List<A2AMessage>? history;

  /// A collection of artifacts generated by the agent during the execution of the task.
  List<A2AArtifact>? artifacts;

  /// Optional metadata for extensions. The key is an extension-specific identifier.
  A2ASV? metadata;

  /// The type of this object, used as a discriminator. Always 'task' for a Task.
  @JsonKey(includeToJson: true, includeFromJson: false)
  String kind = 'task';

  A2ATask();

  factory A2ATask.fromJson(Map<String, dynamic> json) =>
      _$A2ATaskFromJson(json);

  Map<String, dynamic> toJson() => _$A2ATaskToJson(this);

  /// Deep clone.
  A2ATask clone() {
    // Take advantage of the fact we can serialize these classes
    final thisJson = toJson();
    return A2ATask.fromJson(thisJson);
  }
}

/// Represents the status of a task at a specific point in time.
@JsonSerializable(explicitToJson: true)
class A2ATaskStatus {
  /// The current state of the task's lifecycle.
  A2ATaskState state = A2ATaskState.unknown;

  /// An optional, human-readable message providing more details about
  /// the current status.
  A2AMessage? message;

  /// ISO 8601 datetime string indicating when the status was recorded.
  String? timestamp;

  A2ATaskStatus();

  factory A2ATaskStatus.fromJson(Map<String, dynamic> json) =>
      _$A2ATaskStatusFromJson(json);

  Map<String, dynamic> toJson() => _$A2ATaskStatusToJson(this);
}

/// Represents the possible lifecycle states of a Task.
enum A2ATaskState {
  /// The task has been submitted and is awaiting execution.
  @JsonValue('submitted')
  submitted,

  /// The agent is actively working on the task.
  @JsonValue('working')
  working,

  /// The task is paused and waiting for input from the user.
  @JsonValue('input-required')
  inputRequired,

  /// he task has been successfully completed.
  @JsonValue('completed')
  completed,

  /// The task has been canceled by the user.
  @JsonValue('canceled')
  canceled,

  /// The task failed due to an error during execution.
  @JsonValue('failed')
  failed,

  /// The task was rejected by the agent and was not started.
  @JsonValue('rejected')
  rejected,

  /// The task requires authentication to proceed.
  @JsonValue('auth-required')
  authRequired,

  ///  The task is in an unknown or indeterminate state.
  @JsonValue('unknown')
  unknown,
}
