/*
* Package : a2a
* Author : S. Hamblett <steve.hamblett@linux.com>
* Date   : 30/06/2026
* Copyright :  S.Hamblett
*/

part of '../../a2a_types.dart';

/// Represents a single message in the conversation between a user and an agent.
@JsonSerializable(explicitToJson: true)
class A2AMessage {
  /// Identifies the sender of the message. `user` for the client,
  /// `agent` for the service.
  String role = 'agent';

  /// An array of content parts that form the message body. A message can be
  /// composed of multiple parts of different types [A2ATextPart],
  /// [A2ADataPart] or [A2AFilePart].
  List<A2APart> parts = [];

  /// Optional metadata for extensions. The key is an extension-specific identifier.
  A2ASV? metadata;

  /// The URIs of extensions that are present or contributed to this Message.
  List<String>? extensions;

  /// A list of other task IDs that this message references for additional context.
  List<String>? referenceTaskIds;

  /// A unique identifier for the message, typically a UUID, generated by the sender.
  String messageId = '';

  /// The ID of the task this message is part of. Can be omitted for the first message of a new task.
  String? taskId;

  /// The context ID for this message, used to group related interactions.
  String? contextId;

  /// The type of this object, used as a discriminator. Always 'message' for a Message.
  @JsonKey(includeToJson: true, includeFromJson: false)
  String kind = 'message';

  @override
  int get hashCode => messageId.hashCode;

  A2AMessage();

  factory A2AMessage.fromJson(Map<String, dynamic> json) =>
      _$A2AMessageFromJson(json);

  Map<String, dynamic> toJson() => _$A2AMessageToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is A2AMessage &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId;
}
