/*
* Package : a2a
* Author : S. Hamblett <steve.hamblett@linux.com>
* Date   : 10/07/2025
* Copyright :  S.Hamblett
*/

part of '../../types.dart';

/// Mirrors the OpenAPI Security Scheme Object
/// (https://swagger.io/specification/#security-scheme-object)
base class A2ASecurityScheme {}

/// API Key security scheme.
final class A2AAPIKeySecurityScheme extends A2ASecurityScheme {
  /// Description of this security scheme.
  String? description;

  /// The location of the API key. Valid values are "query", "header", or "cookie"
  /// Named 'in' in the TS code, Dart can't use this as its a reserved word..
  String location = '';

  /// The name of the header, query or cookie parameter to be used.
  String? name;
  final String type = 'apiKey';
}

/// HTTP Authentication security scheme.
final class A2AHTTPAuthSecurityScheme extends A2ASecurityScheme {
  /// A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually
  /// generated by an authorization server, so this information is primarily for documentation
  /// purposes.
  String? headerFormat;

  /// Description of this security scheme.
  String? description;

  /// The name of the HTTP Authentication scheme to be used in the Authorization header as defined
  /// in RFC7235. The values used SHOULD be registered in the IANA Authentication Scheme registry.
  /// The value is case-insensitive, as defined in RFC7235.
  String scheme = '';
  final type = 'http';
}

final class A2AOAuth2SecurityScheme extends A2ASecurityScheme {}

final class A2AOpenIdConnectSecurityScheme extends A2ASecurityScheme {}
